spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xuyafei
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: warn
    com.xyf.blog: info
  file:
    name: log/blog-pro.log
server:
  port: 8081


#生产环境